### ISSUE TITLE
[tekstueel] Tikfout

### ISSUE THREAD

**Issue by krijnhoetmer** [fdnd/docs.fdnd.nl#40]
Begeleid moet met dt. (Als voorbeeld voor @CharleyMuhren)

https://github.com/fdnd/docs.fdnd.nl/blob/c27caa1f2010f1087b65316f62d324652ea3be1b/docs/organisatie.md?plain=1#L13

**Comment by ju5tu5** [comment]
Thanks! Ik heb het aangepast.
