### ISSUE TITLE
[tekstueel] Spelfouten in de Read-me

### ISSUE THREAD

**Issue by kosterm14** [fdnd/docs.fdnd.nl#89]
**Aanpassing**
Ik stel aanpassing voor in de Read-me van deze repo op het gebied van spelling om het professioneler te maken.

**Verwijzing**
https://github.com/fdnd/docs.fdnd.nl/blob/c90cdb918ca0c03857bbe2502d92c9b86a1ae3ac/README.md?plain=1#L29

**Fout/Verbetering**
"Hierdoor worden een aantal extenties ondersteund bovenop de standaard Markdown specificatie. "Extenties" moet veranderd worden naar "Extensies"

**Verwijzing**
https://github.com/fdnd/docs.fdnd.nl/blob/c90cdb918ca0c03857bbe2502d92c9b86a1ae3ac/README.md?plain=1#L87

**Fout/Verbetering**
"Je kunt tekst binnnen dezelfde alinea tussen één of twee tildes (~) zetten om het door te halen. "Binnnen" moet veranderd worden naar "Binnen"

**Comment by ju5tu5** [comment]
Thanks voor je opmerking!
